# Chapter One
## 1.5 Numpy

### 导入numpy

In [0]:
import numpy as np

### 生成NumPy数组

In [0]:
x = np.array([1,0, 2.0, 3.0])

In [3]:
x

array([1., 0., 2., 3.])

In [4]:
type(x)

numpy.ndarray

### NumPy的算术运算

In [0]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [6]:
x + y

array([3., 6., 9.])

In [7]:
x - y

array([-1., -2., -3.])

In [8]:
x * y

array([ 2.,  8., 18.])

In [9]:
x / y

array([0.5, 0.5, 0.5])

对应元素的=> element-wise

### NumPy的N维数组

In [0]:
A = np.array([[1,2],[3,4]])

In [11]:
A

array([[1, 2],
       [3, 4]])

In [12]:
A.shape

(2, 2)

In [13]:
A.dtype

dtype('int64')

In [0]:
B = np.array([[3, 0],[0, 6]])

In [15]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [16]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
A * 10

array([[10, 20],
       [30, 40]])

### 广播

![替代文字](https://images2015.cnblogs.com/blog/586070/201605/586070-20160517002735654-1094729362.png)

In [0]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [20]:
A * B

array([[10, 40],
       [30, 80]])

### 访问元素

In [0]:
X = np.array([[51, 55], [14, 19], [0,4]])

In [23]:
X

array([[51, 55],
       [14, 19],
       [ 0,  4]])

In [24]:
X[0]

array([51, 55])

In [25]:
X[0][1]

55

In [26]:
for row in X:
  print(row)

[51 55]
[14 19]
[0 4]


In [0]:
X = X.flatten()

In [28]:
X

array([51, 55, 14, 19,  0,  4])

In [29]:
X[np.array([0, 2, 4])]

array([51, 14,  0])